### ISSUE TITLE
Tests' failing on IE 6, 7 and 8

### ISSUE THREAD

**Issue by igorlima** [blackberry/Alice#46]
[![Selenium Test Status](https://saucelabs.com/browser-matrix/Alice.svg)](https://saucelabs.com/u/Alice)

Created a [branch](https://github.com/igorlima/Alice/tree/test/ci/saucelabs) integrated with SauceLabs to test against the major of browsers. 

The tests are failing on IE 6, 7 and 8.

**Comment by mlantz** [comment]
Its designed to work on IE9 and up. CSS3 isn't supported by those browsers anyway. It runs the animations with CSS3 so IE 6,7,8 are irrelevant.

**Comment by igorlima** [comment]
Thanks.
