### ISSUE TITLE
Remove Use of new Array() Constructor

### ISSUE THREAD

**Issue by boazsender** [blackberry/Alice#7]
I noticed the use of `var elems = new Array(...)`, instead of using the `var myArr = []` literal syntax:

https://github.com/blackberry/Alice/blob/master/js/alice.js#L40

The literal syntax is both more readable and more performant. Constructing an array with `new Array( length )` does not do anything to improve the speed of reading from or operating on the array.

**Comment by ldhasson** [comment]
Absolutely... We haven't done a full code review on some of the newest code.
